In [1]:
import numpy as np
from sklearn import preprocessing 


input_data = np.array([[ 1., -1.,  2.],
                        [ 2.,  0.,  0.],
                        [ 0.,  1., -1.]])

x = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]

In [2]:
d1 = preprocessing.Binarizer(threshold=0.5).transform(input_data)
d1

array([[1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [3]:
input_data.mean(axis=0)

array([1.        , 0.        , 0.33333333])

In [4]:
input_data.std(axis=0)

array([0.81649658, 0.81649658, 1.24721913])

In [5]:
d2 = preprocessing.scale(input_data)
d2

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [6]:
#z = (x-u)/s
d3 = preprocessing.StandardScaler().fit(input_data)
d3

StandardScaler()

In [7]:
d3.mean_

array([1.        , 0.        , 0.33333333])

In [8]:
print(d3.transform(input_data))

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [9]:
#x' = ((x-min)/(max-min))*(new_max - new_min) + new_min

d4 = preprocessing.MinMaxScaler(feature_range=(0,1)).fit_transform(input_data)
d4

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [10]:
#L1

d5 = preprocessing.normalize(input_data, norm='l1')
d5

array([[ 0.25, -0.25,  0.5 ],
       [ 1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.5 , -0.5 ]])

In [11]:
0.25+ -0.25+ 0.5

0.5

In [12]:
1.  +  0.  +  0.

1.0

In [13]:
#L2
d6 = preprocessing.normalize(input_data, norm='l2')
d6

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [14]:
np.sqrt(0.40824829**2 + -0.40824829**2 +0.81649658**2)

0.81649658

In [16]:
#n_categories

x = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]

d7 = preprocessing.OneHotEncoder().fit(x)
d7 = d7.transform([['female','from US','uses Safari'],['male','from Europe', 'uses Safari']]).toarray()
d7

array([[1., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 1.]])

In [17]:
d8 = preprocessing.LabelEncoder()
d8.fit(["paris","paris","tokyo","india"])
d8.classes_

array(['india', 'paris', 'tokyo'], dtype='<U5')

In [18]:
d8.transform(["tokyo","tokyo","paris"])

array([2, 2, 1])