In [1]:
import numpy as np
from sklearn.linear_model import SGDClassifier, SGDRegressor

In [2]:
# -1 -1
# -2 -1
# 1   1
# 2   1

X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])

In [3]:
clf = SGDClassifier(max_iter=1000, tol=1e-3,penalty="elasticnet")
clf.fit(X, y)

SGDClassifier(penalty='elasticnet')

In [4]:
clf.predict([[2,2]])

array([2])

In [5]:
clf.coef_

array([[9.77200712, 9.77200712]])

In [6]:
clf.intercept_

array([-10.])

In [7]:
clf1 = SGDRegressor(max_iter=1000,penalty="elasticnet",loss='huber',tol=1e-3, average=True)
clf1.fit(X, y)

SGDRegressor(average=True, loss='huber', penalty='elasticnet')

In [8]:
clf1.coef_

array([-0.00164713, -0.00106165])